/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecepcionarDocGUI.java
 *
 * Created on 13/09/2012, 01:37:27 AM
 */

package Gui;

import ClassControl.CtrRecepcion;
import ClassEntidad.Dependencia;
import ClassEntidad.DocExterno;
import ClassEntidad.Funcionario;
import ClassEntidad.PerExterna;
import ClassEntidad.Persona;
import ClassEntidad.Sistema;
import javax.swing.JOptionPane;
import util.CparaCombo;

/**
 *
 * @author borisgr04
 */
public class RecepcionarDocGUI extends javax.swing.JFrame implements IRecibir {
    private BuscarPerExtGUI guiPerExt =new BuscarPerExtGUI();
    private PerExterna PerExt= new PerExterna();
    PerExterna pe;
    private int serieTRD;
    CtrRecepcion cd;// = new CtrRecepcion();
    /** Creates new form RecepcionarDocGUI */
    public RecepcionarDocGUI() {
        initComponents();
        inicializar();
        
    }

    void inicializar() {
        //Llena Comobo Box Dependencia
         Funcionario fun= new Funcionario();
         for (Persona f : fun.getFuncionario()) {
            this.depDestinoC.addItem(new CparaCombo(f.getNroIde(), f.getNombres()));
        }
        iniFormularios.mostrarUsuarioActual(autorT);
        Habilitar(false);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        nuevoB = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        cancelB = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        DistribuirB = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        cerrarB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fechaT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nRadicadoB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        docRelacionadoT = new javax.swing.JTextField();
        relDocB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        asuntoT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumenT = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        tVencimintoSp = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        FoliosSp = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        identPerRemB = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nombresPEB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dirPEB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        correoPEB = new javax.swing.JTextField();
        buscarPerExtB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        depDestinoC = new javax.swing.JComboBox();
        autorT = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        nuevoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/New.png"))); // NOI18N
        nuevoB.setText("Nuevo");
        nuevoB.setFocusable(false);
        nuevoB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevoB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBActionPerformed(evt);
            }
        });
        jToolBar1.add(nuevoB);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);

        cancelB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/undo.png"))); // NOI18N
        cancelB.setText("Cancelar");
        cancelB.setFocusable(false);
        cancelB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cancelB);
        jToolBar1.add(jSeparator1);

        DistribuirB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/email-send-icon.png"))); // NOI18N
        DistribuirB.setText("Distribuir");
        DistribuirB.setFocusable(false);
        DistribuirB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DistribuirB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        DistribuirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistribuirBActionPerformed(evt);
            }
        });
        jToolBar1.add(DistribuirB);
        jToolBar1.add(jSeparator2);

        cerrarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Log Out_32x32.png"))); // NOI18N
        cerrarB.setText("Cerrar");
        cerrarB.setFocusable(false);
        cerrarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrarB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(cerrarB);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recepción de Documentos"));

        jLabel1.setText("Fecha y Hora");

        jLabel2.setText("N° Radicado");

        jLabel3.setText("Relacionar Documento");

        relDocB.setText("...");

        jLabel4.setText("Asunto");

        jLabel5.setText("Resumen");

        resumenT.setColumns(20);
        resumenT.setRows(5);
        jScrollPane1.setViewportView(resumenT);

        jLabel10.setText("N° Folio");

        tVencimintoSp.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel6.setText("Tiempo de Rpta (Dias)");

        FoliosSp.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fechaT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nRadicadoB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(docRelacionadoT, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(relDocB))
                            .addComponent(asuntoT, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(FoliosSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tVencimintoSp, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nRadicadoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(docRelacionadoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relDocB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(asuntoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tVencimintoSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoliosSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Remitente"));

        jLabel12.setText("Documento");

        jLabel13.setText("Nombres");

        jLabel14.setText("Dirección");

        jLabel15.setText("Correo");

        buscarPerExtB.setText("...");
        buscarPerExtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPerExtBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(correoPEB)
                    .addComponent(dirPEB, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombresPEB, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identPerRemB, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarPerExtB)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(identPerRemB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPerExtB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nombresPEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dirPEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoPEB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Destino"));

        jLabel7.setText("Dependencia Destino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(476, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(depDestinoC, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(depDestinoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(autorT)
                .addContainerGap(533, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(autorT))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(228, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DistribuirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistribuirBActionPerformed
        // TODO add your handling code here:
        cd= new CtrRecepcion();
        try {
             CparaCombo depDes = (CparaCombo) depDestinoC.getSelectedItem();
            if (depDes == null) {
                JOptionPane.showMessageDialog(this, "Seleccione Destinatario", Sistema.instancia().getNomApp(), JOptionPane.WARNING_MESSAGE);
                return;
            }

            DocExterno d = new DocExterno();
            Funcionario f = new Funcionario();
            d.setAsunto(asuntoT.getText());
            d.setResumen(resumenT.getText());
            d.setPlazoVec(Integer.parseInt(this.tVencimintoSp.getValue().toString()));
            d.setFolios(Integer.parseInt(this.FoliosSp.getValue().toString()));
            d.setIde(pe);
            d.setIdPerDest(depDes.getCodigo());
            d.setIdPerProd(f.getUsuarioActual().getNroIde());
            d.setSerieTRD("01");
           //d.setNomDestino(depDes.getCodigo());
            cd.setDoc(d);
            cd.Guardar();

            if(cd.isValido()){
                this.nRadicadoB.setText(String.valueOf(cd.getDoc().getNoDocumento()));
                JOptionPane.showMessageDialog(this, "Se Guardó el Documento", Sistema.instancia().getNomApp(), JOptionPane.INFORMATION_MESSAGE);
            }
             else{
                JOptionPane.showMessageDialog(this, cd.getMensaje(), Sistema.instancia().getNomApp(), JOptionPane.WARNING_MESSAGE);
             }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), Sistema.instancia().getNomApp(), JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_DistribuirBActionPerformed

    private void buscarPerExtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPerExtBActionPerformed
        // TODO add your handling code here:

     this.guiPerExt.setRdg(this);

     this.guiPerExt.setVisible(true);

    }//GEN-LAST:event_buscarPerExtBActionPerformed

    private void nuevoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBActionPerformed
     this.Habilitar(true);        // TODO add your handling code here:
     this.limipiar();

    }//GEN-LAST:event_nuevoBActionPerformed
private void Habilitar(boolean var){
        this.cancelB.setEnabled(var);
        this.DistribuirB.setEnabled(var);
        this.relDocB.setEnabled(var);
        this.buscarPerExtB.setEnabled(var);

}


private void limipiar (){
this.fechaT.setText("");
this.asuntoT.setText("");
this.docRelacionadoT.setText("");
this.nRadicadoB.setText("");
this.identPerRemB.setText("");
this.nombresPEB.setText("");
this.dirPEB.setText("");
this.tVencimintoSp.setValue(-1);
this.depDestinoC.setSelectedIndex(-1);
this.correoPEB.setText("");
this.FoliosSp.setValue(-1);

}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecepcionarDocGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DistribuirB;
    private javax.swing.JSpinner FoliosSp;
    private javax.swing.JTextField asuntoT;
    private javax.swing.JLabel autorT;
    private javax.swing.JButton buscarPerExtB;
    private javax.swing.JButton cancelB;
    private javax.swing.JButton cerrarB;
    private javax.swing.JTextField correoPEB;
    private javax.swing.JComboBox depDestinoC;
    private javax.swing.JTextField dirPEB;
    private javax.swing.JTextField docRelacionadoT;
    private javax.swing.JTextField fechaT;
    private javax.swing.JTextField identPerRemB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField nRadicadoB;
    private javax.swing.JTextField nombresPEB;
    private javax.swing.JButton nuevoB;
    private javax.swing.JButton relDocB;
    private javax.swing.JTextArea resumenT;
    private javax.swing.JSpinner tVencimintoSp;
    // End of variables declaration//GEN-END:variables

    public void Recibir(Persona o) {
         pe=(PerExterna)o;
         this.dirPEB.setText(pe.getDireccion());
         this.identPerRemB.setText(pe.getNroIde());
         this.nombresPEB.setText(pe.getNombres());
         this.correoPEB.setText(pe.getEmail());


    }

  

}
