/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TramitarGUI.java
 *
 * Created on 13/09/2012, 01:20:43 AM
 */
package Gui;

import ClassControl.CtrTramite;
import ClassEntidad.DistribucionDoc;
import ClassEntidad.Sistema;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author borisgr04
 */
public class BandejaEntGUI extends javax.swing.JFrame implements Observer, TableModelListener {
    //private DefaultTableModel modeloTabla;

    private TablaBandeja modeloTabla;
    DistribucionDoc dd;
    CtrTramite ct= new CtrTramite();

    public void InicializarB() {
        modeloTabla = new TablaBandeja();
        modeloTabla.setLstdoc(Sistema.instancia().getLstDistriDoc());
    }

    /** Creates new form TramitarGUI */
    public BandejaEntGUI() {
        Sistema.instancia().addObserver(this);
        InicializarB();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        AbrirB = new javax.swing.JButton();
        responderB = new javax.swing.JButton();
        archivarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tramite de Documento"));

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Email-Forward-icon.png"))); // NOI18N
        jButton1.setText("Reenviar");

        AbrirB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/open-icon.png"))); // NOI18N
        AbrirB.setText("Abrir");
        AbrirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirBActionPerformed(evt);
            }
        });

        responderB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Email-Reply-icon.png"))); // NOI18N
        responderB.setText("Responder");
        responderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responderBActionPerformed(evt);
            }
        });

        archivarB.setIcon(new javax.swing.ImageIcon("C:\\Users\\borisgr04\\Downloads\\document-archive-icon.png")); // NOI18N
        archivarB.setText("Archivar");
        archivarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AbrirB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(archivarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(responderB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbrirB)
                    .addComponent(archivarB)
                    .addComponent(responderB)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirBActionPerformed
        // TODO add your handling code here:
        //InicializarB();
        //JOptionPane.showMessageDialog(this,"actualizar",Sistema.instancia().getNomApp(), JOptionPane.WARNING_MESSAGE);

        boolean avanzar = true;

        int registro = jTable1.getSelectedRow();
        int columna = jTable1.getSelectedColumn();

        if (registro == -1) {
            avanzar = false;
        } else if (columna == -1) {
            avanzar = false;
        }
        if (avanzar) {
            String strResultado = this.modeloTabla.getValueAt(
                    jTable1.getSelectedRow(),
                    jTable1.getSelectedColumn()).toString();
            JOptionPane.showMessageDialog(null, "Dato seleccionado : " + strResultado);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado un registro");
        }



    }//GEN-LAST:event_AbrirBActionPerformed

    private void archivar() {
        ct.setDd(dd);
        ct.Archivar();
        actualizarGrid();
    }


    private void archivarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivarBActionPerformed
        // TODO add your handling code here:
        if(isSeleccionado())
            archivar();
    }//GEN-LAST:event_archivarBActionPerformed

    private void responderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderBActionPerformed
        // TODO add your handling code here:
       if(isSeleccionado())
        responder();
    }//GEN-LAST:event_responderBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BandejaEntGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirB;
    private javax.swing.JButton archivarB;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton responderB;
    // End of variables declaration//GEN-END:variables



    public void actualizarGrid() {
        modeloTabla = new TablaBandeja();
        modeloTabla.setLstdoc(Sistema.instancia().getLstDistriDoc());
        jTable1.setModel(modeloTabla);
    }

    public void update(Observable o, Object arg) {
        actualizarGrid();
    }

    public void tableChanged(TableModelEvent e) {
        //throw new UnsupportedOperationException("Not supported yet.");
        JOptionPane.showMessageDialog(this, "actualizarTabla", Sistema.instancia().getNomApp(), JOptionPane.WARNING_MESSAGE);
    }

    private void responder() {

        ProducirDocGUI p=new ProducirDocGUI(dd.getDocumento());
        p.setVisible(true);
    }

    private boolean isSeleccionado() {
        int registro = jTable1.getSelectedRow();
        boolean sw=false;
        if (registro >= 0) {
            dd = modeloTabla.getDoc(registro);
            int strResultado = dd.getDocumento().getNoDocumento();
            int r = JOptionPane.showConfirmDialog(this, "Desea Guardar y Enviar el Documento N°" + strResultado, "MessageBox Title", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
                archivar();
                sw=true;
            }
        }
        return sw;
    }
 
}